---
# borg and borgmatic were installed via apt before.
# As we use pipx now, we have to ensure no conflicting apt packages are installed.
- name: Ensure borg and borgmatic are not installed (via apt)
  become: true
  ansible.builtin.apt:
    state: absent
    update_cache: true
    cache_valid_time: 3600  # Do not update if already done in the last hour.
    pkg:
      - borgbackup
      - borgmatic
      
- name: Ensure dependencies (via apt)
  become: true
  ansible.builtin.apt:
    state: present
    update_cache: true
    cache_valid_time: 3600  # Do not update if already done in the last hour.
    pkg:
      - python3-pip
      - python3-venv
      # Needed to install or run borg
      - python3-dev
      - libacl1-dev
      - libacl1
      - libssl-dev
      - liblz4-dev
      - libzstd-dev
      - libxxhash-dev
      - build-essential
      - pkg-config
      - python3-pkgconfig
      # - libfuse-dev  # Needed for llfuse
      # - fuse  # Needed for llfuse
      # - ibfuse3-dev  # Needed for pyfuse3
      # - fuse3  # Needed for pyfuse3

- name: Ensure pipx (via pip)
  ansible.builtin.pip:
    name: pipx==1.7.1
    state: present

- name: Ensure borg (via pipx)
  community.general.pipx:
    name: "borgbackup=={{ borg__borg_version }}"
  tags:
    - molecule-idempotence-notest  # TODO: Somehow this task is not idempotent.

- name: Ensure borgmatic (via pipx)
  community.general.pipx:
    name: "borgmatic=={{ borg__borgmatic_version }}"
  tags:
    - molecule-idempotence-notest  # TODO: Somehow this task is not idempotent.
