---
# TODO: Quick fix as borg was installed as apt dependency of borgmatic before.
#       But we use pipx now.
#       We might want to use pipx also for borg.
- name: Ensure borg apt package
  become: true
  ansible.builtin.apt:
    state: present
    update_cache: true
    cache_valid_time: 3600  # Do not update if already done in the last hour.
    pkg:
      - borgbackup
      
- name: Ensure python3-pip apt package
  become: true
  ansible.builtin.apt:
    state: present
    update_cache: true
    cache_valid_time: 3600  # Do not update if already done in the last hour.
    pkg:
      - python3-pip

- name: Ensure python3-venv apt package
  become: true
  ansible.builtin.apt:
    state: present
    update_cache: true
    cache_valid_time: 3600  # Do not update if already done in the last hour.
    pkg:
      - python3-venv

# Needed to install borgmatic via pipx
- name: Ensure pipx pip package
  ansible.builtin.pip:
    name: pipx==1.2.0
    state: present
    #executable: /usr/local/python3.8/bin/pip3.8

- name: Ensure borgmatic pip package
  community.general.pipx:
    name: "borgmatic=={{ borg__borgmatic_version }}"
    #executable: /usr/local/python3.8/bin/pipx
  tags:
    - molecule-idempotence-notest  # TODO: Somehow this task is not idempotent.
