---
- name: Converge
  hosts: all
  tasks:
    - name: "Include debuglevel.borg"
      ansible.builtin.include_role:
        name: "debuglevel.borg"
      vars:
        borg__encryption_passphrase: "TEST"
        borg__ssh_key_path: "/tmp/sshkey/id_ed25519"
        borg__destinations:
          - host: some-server.example
            port: 22
            type: local
            repository: "/tmp/{{ inventory_hostname }}"
